# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4018b191003e5a944eddb76940742ddc"
name = "qrcode"
handle = "qrcode-208"
application_url = "https://italy-popularity-courses-bit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cofaria-01.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://italy-popularity-courses-bit.trycloudflare.com/auth/callback",
  "https://italy-popularity-courses-bit.trycloudflare.com/auth/shopify/callback",
  "https://italy-popularity-courses-bit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
